### ISSUE TITLE
Cannot add files to Sitelet Website template

### ISSUE THREAD

**Issue by intellifactory-bb** [intellifactory/websharper#192]
Repro:

Create new Sitelet Website project
Right click on a .fs file in solution explorer, choose add above, new item.
No files types are available in the dialog

---
- Bitbucket: https://bitbucket.org/intellifactory/websharper/issue/192
- Originally reported by: Anonymous
- Originally created at: 2013-12-21T16:58:49.214

**Comment by JorgeVV** [comment]
Workaround do not work on VS2017.

**Comment by Tarmil** [comment]
Indeed, VS 2017 has changed how this works, it uses a local registry file instead of the global registry.

[This](https://gist.github.com/Tarmil/1a72147ec3154e245f46f4c4b7f435b8) updated version is working for me, can you confirm that it works for you too?

I also [submitted a PR](https://github.com/Microsoft/visualfsharp/pull/3203) to VisualFSharp so that this would be done by default by the F# Tools.

**Comment by JorgeVV** [comment]
It works. Thanks!

**Comment by Tarmil** [comment]
Btw my PR was merged quickly, so [the Visual F# tools nightly release](https://blogs.msdn.microsoft.com/dotnet/2017/03/14/announcing-nightly-releases-for-the-visual-f-tools/) includes this fix. No more script to run, just install the latest tools and it will work.
