### ISSUE TITLE
Question(s): Lists in RPC results 

### ISSUE THREAD

**Issue by ca-ta** [intellifactory/websharper#334]
Hi guys,

I have an RPC method returning something like this (think railway-style Result)
```
type A = 
   | B of string list
   | C of ...
```
The RPC method can be something as simple as ``` let f() = async { return B ["a"; "b"; "c"] } ```

Trying to traverse the returned list on the client (e.g. by Using List.fold, etc.) triggers a JavaScript runtime error: JavaScript runtime error: Object doesn't support property or method 'GetEnumerator'

It appears the RPC deserializer fails to generate the correct prototype for the deserialized list.

Is this a known limitation? If so:
* what is the recommended approach of returning a non-trivial result to the client?
* is there a way to hack/coerce the result to a working client-side list? I'm not saying this is desirable, but I'm under some time pressure and could use a workaround suggestion :-)
* any suggestions as to how one would approach fixing this (I'm not very familiar with the Websharper code base and could definitely use some hints)

Thanks for a great project!

**Comment by qwe2** [comment]
Hey,

This piece of code should work without a hitch as we use this throughout our applications (mostly for very similar reasons).

Some simple questions as I cannot reproduce the error:
* is this a client-server application (previously Sitelet)?
* which version of WS are you using?
* which browser are you using?
* if you simply try to log the response object in the browser what do you get in the console?

For example this works for me on `WS 3.0.23.104-alpha` in a client-server app: https://gist.github.com/qwe2/1306fdadd7df2593b89b
What are you doing differently?

**Comment by ca-ta** [comment]
Hi István, 

Thank you for looking into this; here's my setup:

* Bundle project
* WebSharper 3.0.12.88-alpha
* WebSharper.UI.Next 3.0.6.65-alpha
* WebSharper.Owin 3.0.7.17-alpha

I have created a new Client-Server project (using the template) and tested a similar scenario to the one that fails for us - and everything works as expected.

I will dig further and let you know what I find. Thanks for helping!

**Comment by qwe2** [comment]
Bundle projects are client-side only, they don't have the "concept" of RPC functions. The RPC attribute has to be specified on server-side functions.

**Comment by ca-ta** [comment]
Oh. Here's how it (partially I guess) works for me:
* I have a library project that contains the RPC functions and the necessary bootstrapping code (such as serving a dummy html that loads the client-side script and initializing the RPC mechanism using Websharper.Owin)
* I am using UI.Next exclusively for the client  - the Bundle project (seems to) do a good job of creating one JavaScript file with all the required client-side code. This script gets loaded by the bootstrap html, and it (again, appears to ) work like a charm.

Does the above  make sense? 

That's what I have been doing (I suppose because I started from the UI.Next samples), and RPC calls from the bundled JavaScript client-side project (seemed to) work after I've enabled RPC on the server by using WebSharper.Owin.

I've used fiddler and it seems that, the issue in my case might be that the $TYPES node in the returned RPC response is empty. Of course I have no idea why that is - and I've just found that I'm using the system in an atypical way.

I could try switching to a "Sites" project (and bundle the JavaScript myself) - do you think it would make a difference?

**Comment by qwe2** [comment]
I'm not entierly familiar with the internals of WebSharper and how exactly RPC calls are handled under the hood so I cannot really comment on your current approach but @Tarmil might be able to help you out. I have no idea what happens when the caller and callee of RPC functions are located in different projects.

On the other hand, using UI.Next with a Sitelet is entirely feasible. The code would be the same apart from the difference that return with the div that contains the inserted `Doc` in the `Web.Control` instance rather than manually inserting it, so

```fsharp
[<JavaScript>]
let Main () = MyDocument |> Doc.RunById("container")
```
becomes
```fsharp
[<JavaScript>]
module Client =
    let Main () = MyDocument |> Doc.AsPagelet
//...
type Control() =
    inherit Web.Control()
    [<JavaScript>]
    override this.Body = Client.Main () :> _
```

and obviously you insert that somewhere in your sitelet. This way the RPC calls will surely work.

**Comment by ca-ta** [comment]
I 've just read my reply and I'd like to clarify that the Web project:
* contains both the client-side and server-side code
* contains the ```<WebSharperProject>Bundle</WebSharperProject>``` node and
* imports the Websharper targets
* references other libraries that are compiled with Websharper and which contain types that are can be used on both client server (using ```JavaScriptAttribute```).

I will continue digging - any insight as to why the $TYPES node might be missing from the RPC response would be of great help. Thanks!

**Comment by ca-ta** [comment]
Thanks! I've replied before seeing your answer. - hopefully @Tarmil can chime in regarding the RPC.
I'm using ```app.UseWebSharperRemotingFromBin``` to enable it.

**Comment by Tarmil** [comment]
So, indeed if your RPCs are defined in the SPA project then you will not have a server-side running to serve them. But it is very simple to point the RPC calls from an SPA to the right server side, you just need to add the following at the beginning of your client-side main definition:

    IntelliFactory.WebSharper.Remoting.EndPoint <- "http://localhost:9000"

(substitute the URL with where your server side is running). This way, you can have a Client-Server Application that only contains your RPC functions, and is referenced and called by your SPA project.

With all this being said, I only recommend such a setup if you have a specific reason for using a plain HTML application (eg. if you wrap it in a PhoneGap mobile application). Otherwise, it is probably simpler to just serve your web page as a sitelet from the Client-Server application.

**Comment by ca-ta** [comment]
Hi @Tarmil,

Thank you for replying.  Yes, we will reuse this in a mobile application. 
Sorry for being thick - there's clearly a disconnect here -this is not about running the RPC server or being able to connect to it:
* I've *always* been able to connect to the server (I *am* getting responses)
* the RPC server *is* running (over OWIN)
* My server-side functions *do* get called and breakpoints are hit, etc.
* The client *does* receive a response - and with the exception of  collections , everything seemed to be just fine.

That  I have made the suggested change - sort of expectedly, it made no difference (as this does not seem to be a connectivity problem).

The one thing that does not seem to work is that the ```$TYPES``` node in the response is an *empty* array. The $DATA is populated just fine. I'm stumped :-(




For reasons I do not understand,

**Comment by ca-ta** [comment]
Here's a simple repro: 

Given this server method:
```
    [<Rpc>]
    let getList() = async { return ["A";"B";"C"] }
```
The vanilla Client-server project returns (and one can fold/map over the returned result client-side):
```
{"$TYPES":[["IntelliFactory","WebSharper","List","T"]],"$DATA":{"$T":0,"$V":{"$":1,"$0":"A","$1":{"$T":0,"$V":{"$":1,"$0":"B","$1":{"$T":0,"$V":{"$":1,"$0":"C","$1":{"$T":0,"$V":{"$":0}}}}}}}}}

```
My project returns (and iterating through  the returned list fails client-side):
```
{"$TYPES":[],"$DATA":{"$V":{"$":1,"$0":"A","$1":{"$V":{"$":1,"$0":"B","$1":{"$V":{"$":1,"$0":"C","$1":{"$V":{"$":0}}}}}}}}}
```
As you can see, the second example contains no types. There are no server-side exceptions or errors as far as I can see, it's just that the List type is missing in action.

**Comment by qwe2** [comment]
Could you please commit  a minimal failing example somewhere because I cannot seem to be able to reproduce the error. What I did last was:
* create an Owin site based on the `Self-Hosted Cleint-Server Application` template and set it to only serve static files and started RPC with `UseWebSharperRemoting(rootDirectory)` on the `AppBuilder`
* declare a single RPC function in this project
* create a new SPA project, reference the previous one and call the Rpc function
* make a static HTML file that references jQuery and the single bundled js file from the latter project

In my case the RPC call works as expected.

**Comment by ca-ta** [comment]
Hi István, 

Thank you for replying - your answer helped me figure it out: I've found the issue - and it's my being very thick, I'm afraid. Here goes:

Remember that I am using ```UseWebSharperRemotingFromBin```? Well, was doing something like this  - which, as it turns out, is retarded: 
```
let l = Assembly.GetExecutingAssembly().Location 
let b = System.IO.Path.GetDirectoryName(location)
b |> app.UseWebSharperRemotingFromBin |> ignore
```
This would result (at least in the case of IISExpress) in a fancy path somewhere in appdata - with the assembly sitting nice and tight alone in the particular folder: no metadata to load (my types are in other libraries) => no types.
Tested this theory by naively pointing the Websharper RPC to the build output bin folder - it works.

Thanks and sorry for being a time drain.

**Comment by ca-ta** [comment]
Here's what works for me, in both production and testing, I hope it helps someone:

```
let uri = UriBuilder(Assembly.GetExecutingAssembly().CodeBase)
let path = Uri.UnescapeDataString(uri.Path);
let binFolder = System.IO.Path.GetDirectoryName(path)
binFolder |> app.UseWebSharperRemotingFromBin |> ignore
```
