### ISSUE TITLE
ref cells are broken

### ISSUE THREAD

**Issue by endeavour** [intellifactory/websharper#411]
Try compiling the and running the following javascript:

    [<JavaScript>]
    let foo() =
      let num = ref 0
      [1;2;3] |> Seq.iter(fun x -> num := !num + x)

Check the browsers console window and you will see the following error:
Uncaught TypeError: t.get_Value is not a function

(tested with WebSharper 3.1.6.156)

**Comment by Tarmil** [comment]
This is strange, I can't seem to replicate this. This is the JavaScript I get with WebSharper 3.1.6.156 for your function:
```javascript
foo:function()
{
 var num;
 num=[0];
 return Seq.iter(function(x)
 {
  num[0]=num[0]+x;
 },List.ofArray([1,2,3]));
}
```

Can you paste here what you get?

**Comment by Jand42** [comment]
Thanks for the report. It is an issue with opening the `WebSharper.UI.Next.Notation` operators, which are shadowing `:=` and `!` so that they work with the `Var` type, but it is incompatible with WebSharper 3.0 `ref` proxy.
Created an issue there: https://github.com/intellifactory/websharper.ui.next/issues/18
