### ISSUE TITLE
No method of versioning javascript

### ISSUE THREAD

**Issue by jnolis** [intellifactory/websharper#722]
I'm currently having an issue with my site where if I make changes to the client-side F# and update the site, people who have viewed the site previously have problems because their browsers don't realize they need to recache the javascript files.

Currently, if I make changes to client side F# that gets compiled into javascript, my HTML refers to `websiteurl.com/Scripts/Websharper/ProjectName.js`. However, if I make changes to the client-side code that adjusts the functions input/output, then browsers viewing the website don't realize they need to recache `ProjectName.js`.

In reading about this, it seems that when getting  the `ProjectName.js` file one could use query strings like `websiteurl.com/Scripts/Websharper/ProjectName.js?version=4` to force a re-cache, but so far as I can tell there is no way in websharper to put a query string into the javascript file calls.

**Comment by granicz** [comment]
This is indeed a useful feature to have, and we have been considering ways to implement this. Curious, if you had a way to put a `version` flag on generated JavaScript files, how would you imagine those versions be generated/assigned?

**Comment by jnolis** [comment]
Could you have a "version" that is just a hash of the compiled code? The versioning order doesn't matter, you just need to tell it something is different.

Do you have any recommendations for near term fixes?

________________________________

**Comment by granicz** [comment]
I think the hash can work.  We also have to consider multi-project solutions with multiple WebSharper libraries and how to differentiate those from external libraries that might otherwise be [referenced via CDN](http://www.websharper.com/blog-entry/4630/websharper-3-6-released-with-cdn-support).

**Comment by giuliohome** [comment]
Mentioning this issue on [gitter](https://gitter.im/intellifactory/websharper?at=5dc88e6fb95ae413dcb58053)
Last friday I still experience a cache issue on chrome that refused to reload the new version from the server ... is the `?h=` I see next to the main script under WebSharper folder an effect of this commit? Can I force a change somehow when I update the content of my client fs? It seems that the number stays the same ...

**Comment by giuliohome** [comment]
I suspect that maybe the problem is that Chrome cachine is now more aggressive and the change of an hash parameter is not enough to ensure that the script is not cached, at least this [post on SO](https://stackoverflow.com/questions/41902195/chrome-not-updating-cache-javascript-files) seems to confirm a problem like that: they are introducing a real change in the script name, before `.js`. Is this something we should consider?

**Comment by giuliohome** [comment]
Now I think I understand what happened. I forgot to deploy the js initially and when I deployed that a few minutes after my chrome browser already cached the hash that is in the caller so it is in the dll previously deployed.
Ok that settles my doubt. It seems that the issue is really closed and there is nothing else to do here
