### ISSUE TITLE
char.ToString() puts code into the string instead of char

### ISSUE THREAD

**Issue by Martin521** [intellifactory/websharper#736]
F#:
`'1'.ToString() = "1"`
Websharper:
`'1'.ToString() = "49"`

**Comment by Jand42** [comment]
Thanks for the report!

Way back it was decided that `char` is proxied by `Number`s, so that arithmetics work on them without conversions in the generated code. F# `string` function and `String` module and type methods do the conversion back to string.

Possible fixes (alternatives):
1. Use same logic as macro for `string` function for every `ToString` call. This would make `'1'.ToString()` to evaluate to `"1"` when used from both languages. `(box '1').ToString()` would still be `"49"`.
2. Switch proxy for `char` to be a 1-length `String`. For keeping all current features, this requires changing all proxies and RPC de/serializer logic related to `char` handling.

**Comment by granicz** [comment]
@Jand42 Not sure if I like either options.  BTW, `(box '1').ToString()` should also be `1`.

**Comment by Martin521** [comment]
@granicz Sure. Like with other some other incompatibilities, I have found workarounds, no problem. But having to find these issues in correct F# code makes Websharper less fun. And it makes porting, or maintaining "dual use" code, more difficult.
BTW Websharper / UI.Next is amazing, I really love it.

**Comment by Jand42** [comment]
Option 2 was implemented. `System.Char` is now translates to a 1-length string. A lot of string operations become a bit faster because of removing unneeded to/from conversions of char codes. Char arithmetic and range is still supported correctly with special handling.
